package com.distributed_payment.payment.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    private String id; // UUID generated by the application

    // These store the Customer/Merchant id (i.e. an "owner id"), NOT a wallets.id.
    // A bare owner id is ambiguous on its own (customer #3 and merchant #3 both
    // exist), so the owner type travels alongside it.
    @Column(name = "sender_owner_id", nullable = false)
    private Long senderOwnerId;

    @Column(name = "sender_owner_type", nullable = false, length = 20)
    private String senderOwnerType;

    @Column(name = "receiver_owner_id", nullable = false)
    private Long receiverOwnerId;

    @Column(name = "receiver_owner_type", nullable = false, length = 20)
    private String receiverOwnerType;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(nullable = false, length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;

    @Column(name = "idempotency_key", nullable = false, unique = true)
    private String idempotencyKey;

    @Column(name = "error_message")
    private String errorMessage;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
